### ISSUE TITLE
portfolio-media-queries-todo

### ISSUE THREAD

**Issue by MrBrandtCox** [MrBrandtCox/Portfolio-brandt-cox#1]
Fix media queries in portfolio repo so the display fits the width of laptop.

**Comment by abitsalihu** [comment]
Hey @MrBrandtCox, I would like to help you with fixing media queries and fixing additional code so the website doesn't overflow on the x-axis (horizontal). :)

**Comment by MrBrandtCox** [comment]
@abitsalihu That would be amazing! I've been struggling to fix that. Do I need to allow a setting for you to contribute?

**Comment by abitsalihu** [comment]
@MrBrandtCox no need, I will work on it and then at the end, I will send a pull request which u can just merge it.
If you don't know how to do that, don't worry I will help you. :)

**Comment by MrBrandtCox** [comment]
@abitsalihu thanks, you're awesome!

**Comment by MrBrandtCox** [comment]
Hey, any luck? Also I just submitted a new issue with my deployment. Profile-img isn't showing. You're welcome to take a whack at it if you want.
